name: Deployment Excercise
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: nmp run build
      - name: Dploy code
        run: echo " Deploying..".
